name: altruist
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ^3.5.0

dependencies:
  audioplayers: ^6.4.0
  animate_do: ^4.2.0
  bloc: ^8.1.4
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0
  moon_design: ^1.1.0
  shared_preferences: ^2.5.3
  flutter_neumorphic: ^3.2.0
  flutter_svg: ^2.0.10+1 # Add this line (check for latest version if needed)
  sliding_up_panel: ^2.0.0+1 # Add this line (check for latest version if needed)
  path_provider: ^2.1.5
  permission_handler: ^11.4.0
  # google_speech: ^2.2.0 # Replaced by Deepgram
  google_generative_ai: ^0.4.6
  screenshot: ^3.0.0
  http: ^1.3.0
  mic_stream: ^0.7.2
  web_socket_channel: ^3.0.2 # Added for Deepgram
  camera: ^0.11.0 # Added for camera functionality
  flutter_sound: ^9.28.0

dev_dependencies:
  bloc_test: ^9.1.7
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  very_good_analysis: ^6.0.0

flutter:
  uses-material-design: true
  generate: true

  # Add these lines:
  assets:
    - assets/icons/
    - assets/fonts/

  fonts:
    - family: Alliance No. 1
      fonts:
        - asset: assets/fonts/alliance-no-1-regular.woff
        - asset: assets/fonts/alliance-no-1-medium.woff
          weight: 500 # Medium weight
